Repository nebari-dev/jupyterlab-jhub-apps, pull requests merged in 2024-10, with the labels that each got.

#8 Add deploy app label to toolbar
  schema/commands.json
  style/base.css
  ui-tests/tests/jupyterlab_jhub_apps.spec.ts-snapshots/notebook-toolbar-before-click-linux.png
Labels: feature

#9 Add button to deploy app from file editor
  schema/commands.json
  ui-tests/tests/jupyterlab_jhub_apps.spec.ts
  ui-tests/tests/jupyterlab_jhub_apps.spec.ts-snapshots/file-editor-toolbar-before-click-linux.png
Labels: feature

#10 Add snapshots to README
  README.md
Labels: documentation

#12 Add main area widget (form in headless mode) with state restoration
  schema/commands.json
  src/__tests__/jupyterlab_jhub_apps.spec.ts
  src/index.ts
  src/utils.ts
  ui-tests/tests/jupyterlab_jhub_apps.spec.ts
  ui-tests/tests/jupyterlab_jhub_apps.spec.ts-snapshots/multiple-tabs-darwin.png
  ui-tests/tests/jupyterlab_jhub_apps.spec.ts-snapshots/multiple-tabs-linux.png
  ui-tests/tests/jupyterlab_jhub_apps.spec.ts-snapshots/notebook-context-menu-with-deploy-app-linux.png
Labels: feature

#13 Bump version to 0.2.0
  package.json
Labels: maintenance

#20 Update sandbox attribute to allow form submission and popup open
  src/index.ts
Labels: feature

#19 Add schema so that properties are correctly rendered by UI
  schema/commands.json
Labels: feature

#21 Add rocket icon to tab
  src/index.ts
  ui-tests/tests/jupyterlab_jhub_apps.spec.ts-snapshots/multiple-tabs-linux.png
Labels: feature

#23 Bump version to 0.3.0
  package.json
Labels: maintenance
